trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    repository: 'adarshmurali/aadya_nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'AdarshDockerHub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'rm'
