trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    repository: 'adarshmurali/aadya_nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: CopyFiles@2
  inputs:
    Contents: '**/docker-compose.yml'''
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

