trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    repository: 'adarshmurali/aadya_nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh1'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: '**/docker-compose.yml'
    targetFolder: '/home/azureuser'
    readyTimeout: '20000'

